[project]
name = "O-RAP"
version = "0.1.0"
description = "Resource-Aware O-RAN Planning Through an Empirical O-DU Cost Model Based on Fanout and Workload"
authors = [
    {name = "Lindalvo Neto",email = "netobrpa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "websocket-client",
    "chardet",
    "pyomo (>=6.9.5,<7.0.0)",
    "unidecode (>=1.3,<2.0)",
    "pandas (>=2.3,<3.0)",
    "numpy",
    "gurobipy (>=13.0.1,<14.0.0)",
    "geopandas",
    "contextily",
    "matplotlib",
    "shapely",
    "statsmodels",
    "scipy",
    "scikit-learn"
]

[tool.poetry]
packages = [{ include = "src" },{ include = "common", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
