[project]
name = "O-RAP"
version = "0.1.0"
description = "Resource-Aware O-RAN Planning Through an Empirical O-DU Cost Model Based on Fanout and Workload"
authors = [
    {name = "Lindalvo Neto",email = "netobrpa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "websocket-client"
]

[tool.poetry]
packages = [{ include = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
